batch_size: 1
num_devices: 1
momentum_base: 0.996
momentum_max: 1.0
momentum_increase: true
dataset: splited_data
eval_metric:
  - nmi
  - acc
  - ari
whole_dataset: true
encoder_name: resnet34
epochs: 1
feat_dim: 256
hidden_size: 4096
#img_size: 96
img_size: 128
lambda_predictor_lr: 10
learning_rate: 0.05
learning_eta_min: 0.
reassign: 1
save_freq: 1
save_checkpoints: true
shuffling_bn: true
symmetric: true
temperature: 0.5
data_folder: /home/nguyen/NTT/OCR/ProPos/DATA/
#use_gaussian_blur: false
use_gaussian_blur: false
warmup_epochs: 50
weight_decay: 0.0005
dist: true
data_resample: true
v2: true
#byol_transform: true
test_resized_crop: false

model_name: propos
cluster_loss_weight: 0.1
latent_std: 0.001

wandb: true
project_name: "clustering_archives_local"
entity: "21020408"
